version: "3"

services:

################################################################################
# app
################################################################################

    app:
        container_name: "${COMPOSE_PROJECT_NAME}_app"
        build:
            context: .
            dockerfile: .infrastructure/app/Dockerfile
            args:
                APP_ENV: "${APP_ENV}"
        ports:
            - "80:80"
        volumes:
            - ".:/app"
        depends_on:
            db:
                condition: service_healthy
            cache:
                condition: service_healthy

################################################################################
# cache
################################################################################

    cache:
        container_name: "${COMPOSE_PROJECT_NAME}_cache"
        build: ./.infrastructure/cache
        volumes:
            - "cache:/data"
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            retries: 3
            timeout: 5s

################################################################################
# db
################################################################################

    db:
        container_name: "${COMPOSE_PROJECT_NAME}_db"
        build: ./.infrastructure/db
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        environment:
            MYSQL_ROOT_PASSWORD: "${COMPOSE_PROJECT_NAME}"
            MYSQL_DATABASE: "${COMPOSE_PROJECT_NAME}"
            MYSQL_USER: "${COMPOSE_PROJECT_NAME}"
            MYSQL_PASSWORD: "${COMPOSE_PROJECT_NAME}"
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
        volumes:
            - "db:/var/lib/mysql"
            - "./.infrastructure/db/init:/docker-entrypoint-initdb.d"
        ports:
            - 3306:3306
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-p${COMPOSE_PROJECT_NAME}"]
            retries: 3
            timeout: 5s

################################################################################
# dbadmin
################################################################################

    dbadmin:
        container_name: "${COMPOSE_PROJECT_NAME}_dbadmin"
        build: ./.infrastructure/dbadmin
        ports:
            - "8080:8080"

################################################################################
# mail
################################################################################

    mail:
        container_name: "${COMPOSE_PROJECT_NAME}_mail"
        build: ./.infrastructure/mail
        ports:
            - "8025:8025"

################################################################################
# volumes
################################################################################

volumes:
    db:
    cache:
